 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: backend 
   labels:
     app: backend
     version: latest
   annotations:
     prometheus.io/scrape: "true"
     prometheus.io/path: "/metrics"
     prometheus.io/port: "8000"
 spec:
   selector:
     matchLabels:
       app: backend
   replicas: 1
   template:
     metadata:
       labels:
         app: backend
         version: latest
     spec:
       containers:
       - name: backend
         image: gcr.io/marianotests/acme-docker-repo/acme-backend:latest
         env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
         ports:
         - containerPort: 5000
         livenessProbe:
           httpGet:
             path: /health/live
             port: 5000
           initialDelaySeconds: 5
           periodSeconds: 20
         readinessProbe:
           httpGet:
             path: /health/ready
             port: 5000
           initialDelaySeconds: 7
           periodSeconds: 20