 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: backend
   labels:
     app: backend
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: backend
   strategy: {}
   template:
     metadata:
       labels:
         app: backend
         network-backend: "true"
         network-frontend: "true"
     spec:
       containers:
       - name: backend
         image: gcr.io/marianotests/acme-docker-repo/acme-backend:latest
         env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: secret
         ports:
         - containerPort: 5000
         resources: {}
       restartPolicy: Always
         