steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build frontend
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/acme-containers/acme-frontend:latest', 'frontend/.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/acme-containers/acme-frontend:latest' ]

- name: 'gcr.io/cloud-builders/docker'
  id: Build backend
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/acme-containers/acme-backend:latest', 'backend/.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/acme-containers/acme-backend:latest' ]

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy manifests
  args: [ 'apply', '-f', 'k8s/' ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-d'
  - 'CLOUDSDK_CONTAINER_CLUSTER=acme-cluster'