steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build frontend
  args: [ 'build', '-t', 'gcr.io/marianotests/acme-docker-repo/acme-frontend:$SHORT_SHA', 'frontend/.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/marianotests/acme-docker-repo/acme-frontend:$SHORT_SHA' ]

- name: 'gcr.io/cloud-builders/docker'
  id: Build backend
  args: [ 'build', '-t', 'gcr.io/marianotests/acme-docker-repo/acme-backend:$SHORT_SHA', 'backend/.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/marianotests/acme-docker-repo/acme-backend:$SHORT_SHA' ]

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args: [ 'apply', '-f', 'frontend/k8s/kubernetes.yaml backend/k8s/kubernetes.yaml' ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=eu-west3-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  - 'VERSION=$SHORT_SHA'