apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    name: db
  namespace: acme-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
      - name: db
        image: mysql:5.7
        args:
        - "--ignore-db-dir=lost+found"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: secret
        ports:
          - name: db
            containerPort: 3306   
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
          readOnly: true
        - name: mysql-data-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
      - name: mysql-data-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
            