 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: web
   labels:
     app: web
     version: latest
   annotations:
     prometheus.io/scrape: "true"
     prometheus.io/path: "/metrics"
     prometheus.io/port: "8000"
 spec:
   selector:
     matchLabels:
       app: web
   replicas: 1
   template:
     metadata:
       labels:
         app: web
         version: latest
     spec:
       containers:
       - name: frontend
         image: gcr.io/marianotests/acme-docker-repo/acme-frontend:latest
         resources: {}
         ports:
         - containerPort: 80
