 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: frontend 
   labels:
     app: frontend
     version: latest
   annotations:
     prometheus.io/scrape: "true"
     prometheus.io/path: "/metrics"
     prometheus.io/port: "8000"
 spec:
   selector:
     matchLabels:
       app: frontend
   replicas: 1
   template:
     metadata:
       labels:
         app: frontend
         version: latest
     spec:
       containers:
       - name: frontend
         image: gcr.io/marianotests/acme-docker-repo/acme-frontend:latest
         ports:
         - containerPort: 8080
         livenessProbe:
           httpGet:
             path: /health/live
             port: 8080
           initialDelaySeconds: 5
           periodSeconds: 20
         readinessProbe:
           httpGet:
             path: /health/ready
             port: 8080
           initialDelaySeconds: 7
           periodSeconds: 20