 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: frontend
   labels:
     app: frontend
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: frontend
   strategy: {}
   template:
     metadata:
       labels:
         network-frontend: "true"
         app: frontend
     spec:
       containers:
       - name: frontend
         image: gcr.io/marianotests/acme-docker-repo/acme-frontend:latest
         ports:
         - containerPort: 80
         resources: {}
       restartPolicy: Always
       
