apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme
      tier: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: acme
        tier: frontend
        network-frontend: "true"
    spec:
      containers:
      - name: frontend
        image: gcr.io/marianotests/acme-docker-repo/acme-frontend:latest
        env:
        - name: NODE_ENV
          value: production
        - name: BACKEND_API
          value: "backend:5000"
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
       
