apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-frontend
spec:
  podSelector:
    matchLabels:
      network-frontend: "true"
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          network-frontend: "true"
  egress:
    - to:
      - podSelector:
          matchLabels:
            network-frontend: "true"
            